'use strict';

/**
 * Shared Lingui ESLint rules (flat config).
 * @returns {Record<string, import('eslint').Linter.RuleEntry>}
 */
function linguiRules() {
  return {
    'lingui/no-unlocalized-strings': [
      'error',
      {
        ignore: [
          '^[A-Z0-9_-]+$',
          '^[a-z]+(\\.[a-z0-9-]+)+$',
          '^#[0-9a-fA-F]{3,8}$',
          // expo-router / React Navigation — not user-facing copy
          '^fade$',
          '^sso-callback$',
        ],
        ignoreNames: [
          'testID',
          'nativeID',
          'id',
          'key',
          'role',
          'type',
          'name',
          'src',
          'href',
          'fontFamily',
          'variant',
          'color',
          'intent',
          'icon',
          'displayName',
          'accessibilityRole',
          'aria-level',
          'numberOfLines',
          'ellipsizeMode',
          'pathname',
          'presentation',
          'anchor',
          'background',
          'foreground',
          'backgroundColor',
          'borderColor',
          'borderStyle',
          'borderTopColor',
          'borderBottomColor',
          'borderLeftColor',
          'borderRightColor',
          'tintColor',
          'd',
          'stroke',
          'strokeLinecap',
          'strokeLinejoin',
          'strokeDasharray',
          'fill',
          'fillRule',
          'flexDirection',
          'flexWrap',
          'align',
          'alignItems',
          'alignSelf',
          'alignContent',
          'centerAlign',
          'justify',
          'justifyContent',
          'justifyItems',
          'justifySelf',
          'placeContent',
          'placeItems',
          'placeSelf',
          'position',
          'display',
          'overflow',
          'overflowX',
          'overflowY',
          'textAlign',
          'textAlignVertical',
          'textTransform',
          'textDecoration',
          'textDecorationLine',
          'textDecorationStyle',
          'fontWeight',
          'fontStyle',
          'fontSize',
          'lineHeight',
          'letterSpacing',
          'cursor',
          'pointerEvents',
          'resizeMode',
          'objectFit',
          'whiteSpace',
          'wordBreak',
          'visibility',
          'userSelect',
          'autoCapitalize',
          'autoComplete',
          'autoCorrect',
          'keyboardType',
          'returnKeyType',
          'inputMode',
          'enterKeyHint',
          'spellCheck',
          'segments',
          'mode',
          'kind',
          'status',
          'state',
          'method',
          'event',
          'eventName',
          'gestureName',
          'animationType',
          'provider',
          'action',
          'placement',
          'orientation',
          'direction',
          'size',
          'shape',
          'tone',
          'severity',
          'level',
          'tag',
          'category',
          { regex: { pattern: 'className', flags: 'i' } },
          { regex: { pattern: 'TestID$', flags: '' } },
          { regex: { pattern: 'testID$', flags: '' } },
          'animation',
          'presentation',
          'anchor',
          'options',
        ],
        ignoreFunctions: [
          'console.*',
          '*.includes',
          '*.startsWith',
          '*.endsWith',
          '*.indexOf',
          '*.match',
          '*.test',
          'require',
          'asLocalized',
          'JSON.stringify',
          'String',
          'i18n.loadAndActivate',
          'i18n._',
          'window.addEventListener',
          'window.removeEventListener',
          'document.addEventListener',
          'document.removeEventListener',
          'addEventListener',
          'removeEventListener',
          'dispatchEvent',
          'localStorage.getItem',
          'localStorage.setItem',
          'localStorage.removeItem',
          'sessionStorage.getItem',
          'sessionStorage.setItem',
          'sessionStorage.removeItem',
          'assert',
          'assert.*',
          'crash',
          'crash.*',
          'invariant',
          '*.error',
          '*.warn',
          '*.info',
          '*.debug',
          '*.log',
          '*.trace',
          'useLogger',
          'Error',
          'TypeError',
          'RangeError',
          'SyntaxError',
          'cancelAll',
          'AbortController',
          'clearLocalDatabaseAndReload',
          'usePatchDbLocalDataActions',
          'createApiClient',
          'createSecureStorage',
          'useDependency',
          'registerValue',
          'registerFactory',
          'setSurface',
          'setPreference',
          'setFilter',
          'setMode',
          'setKey',
          'setStyle',
          'setStatus',
          'setState',
          'setVariant',
          'useState',
          'setSelected',
          'nav',
          'router.push',
          'router.replace',
          'router.navigate',
          'router.back',
          'router.prefetch',
          'router.dismissTo',
          'router.dismiss',
          'router.dismissAll',
          'router.canDismiss',
          'router.canGoBack',
          'fetch',
          'URL',
          'URLSearchParams',
          'new URL',
          'new URLSearchParams',
        ],
        useTsTypes: false,
        ignoreMethodsOnTypes: ['Map.get', 'Map.has', 'Set.has'],
      },
    ],
    'lingui/t-call-in-function': 'error',
    'lingui/no-trans-inside-trans': 'error',
    'lingui/no-expression-in-message': 'error',
    'lingui/no-single-tag-to-translate': 'error',
    'lingui/no-single-variables-to-translate': 'error',
  };
}

module.exports = { linguiRules };
